/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_C_H_RPCGEN
#define _RPC_C_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct client_input {
	int number;
	int convertTo;
};
typedef struct client_input client_input;

#define CONVERSOR_PROG 123
#define CONVERSOR_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define convert 1
extern  int * convert_1(client_input *, CLIENT *);
extern  int * convert_1_svc(client_input *, struct svc_req *);
extern int conversor_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define convert 1
extern  int * convert_1();
extern  int * convert_1_svc();
extern int conversor_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_client_input (XDR *, client_input*);

#else /* K&R C */
extern bool_t xdr_client_input ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_C_H_RPCGEN */
