/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpc_c.h"

bool_t
xdr_client_input (XDR *xdrs, client_input *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->number))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->convertTo))
		 return FALSE;
	return TRUE;
}
